# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Localcinema < Formula
  desc "Lightweight LAN video streaming server"
  homepage "https://github.com/raojinlin/localcinema"
  version "0.0.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/raojinlin/localcinema/releases/download/v0.0.5/localcinema_0.0.5_darwin_amd64.zip"
      sha256 "82a74b8913e0cfafcc9197364a383e9408c492004e30749438177d235ab8cdba"

      define_method(:install) do
        bin.install "localcinema"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/raojinlin/localcinema/releases/download/v0.0.5/localcinema_0.0.5_darwin_arm64.zip"
      sha256 "69c483109c931e94e6125843b35e1d978d65b899f85ea9afcd120baa621b8d36"

      define_method(:install) do
        bin.install "localcinema"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/raojinlin/localcinema/releases/download/v0.0.5/localcinema_0.0.5_linux_amd64.tar.gz"
      sha256 "7a7395781484ae19b5cc3f6e05c95e614489a45559a83465eee37a23615aa439"
      define_method(:install) do
        bin.install "localcinema"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/raojinlin/localcinema/releases/download/v0.0.5/localcinema_0.0.5_linux_arm64.tar.gz"
      sha256 "fb461e1a09b036ac49a517c53eb05bfc2852edb4a338cf9a317ba865a1dd9d68"
      define_method(:install) do
        bin.install "localcinema"
      end
    end
  end
end
