# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Localcinema < Formula
  desc "Lightweight LAN video streaming server"
  homepage "https://github.com/raojinlin/localcinema"
  version "0.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/raojinlin/localcinema/releases/download/v0.0.2/localcinema_0.0.2_darwin_amd64.zip"
      sha256 "f1086a33b836e397b321129b3df6a937ea2e3a9f58bf07dbc4314feb6b8435be"

      def install
        bin.install "localcinema"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/raojinlin/localcinema/releases/download/v0.0.2/localcinema_0.0.2_darwin_arm64.zip"
      sha256 "b6a1595a6ab0f91cc75f5661b7ac9004312434076ab24b5b625777b3bf2cb4df"

      def install
        bin.install "localcinema"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/raojinlin/localcinema/releases/download/v0.0.2/localcinema_0.0.2_linux_amd64.tar.gz"
      sha256 "033e3c045741d34ee090608ae492acb3d253a6d025ed88d1ca13d95efd2316ac"
      def install
        bin.install "localcinema"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/raojinlin/localcinema/releases/download/v0.0.2/localcinema_0.0.2_linux_arm64.tar.gz"
      sha256 "1682a120df195a497a7ab7532fa01cc86d5f21cae56467595e3aefebbd6b86f8"
      def install
        bin.install "localcinema"
      end
    end
  end
end
